# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'
inhibit_all_warnings!
install! 'cocoapods',
  disable_input_output_paths: true,
  generate_multiple_pod_projects: true

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Example
  pod 'YYKit', '1.0.9'
  pod 'DMEncrypt', :path => '../../DMEncrypt'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
